//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WWWC.rc
//
#define ID_ALLYES                       3
#define ID_BUTTON_SAVEOPTION            3
#define ID_ALLNO                        5
#define IDI_ICON_MAIN                   101
#define IDR_MENU_MAIN                   102
#define IDI_ICON_INET                   103
#define IDC_CURSOR_SEP                  104
#define IDI_ICON_UP                     108
#define IDI_ICON_ERROR                  109
#define IDI_ICON_TIMEOUT                110
#define IDI_ICON_NO                     111
#define IDI_ICON_CHECK                  112
#define IDI_ICON_WAIT                   113
#define IDI_ICON_DIRUP                  119
#define IDR_MENU_POPUP                  123
#define IDR_ACCELERATOR_WWWC            124
#define IDR_TOOLBAR                     125
#define IDR_ACCELERATOR_FIND            125
#define IDD_DIALOG_ANI                  130
#define IDB_BITMAP_ANI                  131
#define IDD_DIALOG_UP                   135
#define IDI_ICON_UPCHILD                138
#define IDI_ICON_CHECKCHILD             139
#define IDD_DIALOG_PROTOCOL             140
#define IDD_DIALOG_DLLLIST              141
#define IDD_DIALOG_PRPTOCOLEDIT         142
#define IDI_ICON_RECYCLER               144
#define IDI_ICON_RECYCLER_USE           145
#define IDI_ICON_NOCHECK                146
#define IDD_DIALOG_SETAUTOTIME          148
#define IDI_ICON_NOAUTOTIME             149
#define IDI_ICON_MAIN_CHECK             150
#define IDD_DIALOG_OPTION               151
#define IDD_DIALOG_FOLDER               152
#define IDD_DIALOG_AUTOTIME             153
#define IDD_DIALOG_TOOLLIST             157
#define IDD_DIALOG_TOOL_EXE             158
#define IDD_DIALOG_TITLE                159
#define IDB_BITMAP_UMI                  167
#define IDB_BITMAP_TEXT                 169
#define IDB_BITMAP_SIGN                 170
#define IDD_DIALOG_COPYMSG              172
#define IDI_ICON_COPY                   173
#define IDD_DIALOG_FIND                 174
#define IDD_DIALOG_FINDNAME             175
#define ID_KEY_EDITNAME                 176
#define IDC_CURSOR_HAND                 180
#define IDD_DIALOG_TOOL_DLLLIST         181
#define IDD_DIALOG_ITEM                 182
#define IDD_DIALOG_FINDITEM             183
#define IDD_DIALOG_SELECTFOLDER         184
#define IDD_DIALOG_SELECTDLL            185
#define IDI_ICON_NON                    187
#define IDD_DIALOG_SELECTICON           196
#define WWWC_LIST                       1002
#define IDC_BUTTON_WAIT                 1003
#define IDC_STATIC_MSG                  1004
#define IDC_BUTTON_VIEW                 1005
#define IDC_BUTTON_INFO                 1006
#define IDC_LIST_PROTOCOL               1007
#define IDC_BUTTON_ADD                  1008
#define IDC_STATIC_URL3                 1008
#define IDC_BUTTON_DELETE               1009
#define IDC_BUTTON_TREESET              1010
#define IDC_BUTTON_PEDIT                1010
#define IDC_EDIT_UPDATE                 1010
#define IDC_BUTTON_EDIT                 1011
#define IDC_LIST_DLLENTRY               1012
#define IDC_STATIC_FILENAME             1013
#define IDC_EDIT_TITLE                  1014
#define IDC_EDIT_DLL                    1015
#define IDC_EDIT_LOCATE                 1015
#define IDC_EDIT_CHECKURL               1015
#define IDC_BUTTON_DLLSELECT            1016
#define IDC_EDIT_MAKEDAY                1016
#define IDC_EDIT_VIEWURL                1016
#define IDC_EDIT_HEAD                   1017
#define IDC_EDIT_COMMENT                1017
#define IDC_EDIT_ICONFILE               1018
#define IDC_EDIT_ICONINDEX              1019
#define IDC_BUTTON_ICONSELECT           1020
#define IDC_LIST_AUTOTIME               1020
#define IDC_RADIO1                      1021
#define IDC_EDIT_UPICONFILE             1021
#define IDC_RADIO2                      1022
#define IDC_BUTTON_UPICONSELECT         1022
#define IDC_RADIO3                      1023
#define IDC_EDIT_UPICONINDEX            1023
#define IDC_RADIO4                      1024
#define IDC_RADIO5                      1025
#define IDC_EDIT_DAY                    1026
#define IDC_RADIO6                      1027
#define IDC_RADIO7                      1028
#define IDC_RADIO8                      1029
#define IDC_RADIO9                      1030
#define IDC_RADIO10                     1031
#define IDC_RADIO11                     1032
#define IDC_RADIO12                     1033
#define IDC_EDIT_HOU                    1034
#define IDC_EDIT_MIN                    1035
#define IDC_STATIC_HOU                  1037
#define IDC_STATIC_MIN                  1038
#define IDC_STATIC_DAY                  1039
#define IDC_CHECK_NO                    1044
#define IDC_CHECK_NOCHECK               1045
#define IDC_CHECK_FOLDER_DEF            1046
#define IDC_EDIT_CHECKITEMCNT           1047
#define IDC_CHECK_FOLDER_NOCHECK        1048
#define IDC_STATIC_TYPE                 1050
#define IDC_STATIC_ICON                 1056
#define IDC_CHECK_TRAY                  1057
#define IDC_CHECK_UPMSG                 1058
#define IDC_CHECK_TRAYWINSHOW           1059
#define IDC_CHECK_UPSND                 1060
#define IDC_EDIT_WAVEFILE               1061
#define IDC_BUTTON_BROWS                1062
#define IDC_BUTTON_PLAY                 1063
#define IDC_CHECK_STARTCHECK            1064
#define IDC_BUTTON_UP                   1068
#define IDC_BUTTON_DOWN                 1069
#define IDC_LIST_TOOL                   1070
#define IDC_EDIT_FILENAME               1071
#define IDC_EDIT_COMMANDLINE            1072
#define IDC_CHECK_ITEMMENU              1073
#define IDC_EDIT_PROTOCOL               1074
#define IDC_CHECK_WINDOWMENU            1075
#define IDC_EDIT_MENUINDEX              1076
#define IDC_CHECK_START                 1077
#define IDC_CHECK_END                   1078
#define IDC_CHECK_CHECHSTART            1079
#define IDC_CHECK_CHECKEND              1080
#define IDC_CHECK_INITICON              1082
#define IDC_CHECK_SYNC                  1083
#define IDC_CHECK_MENUDEFAULT           1084
#define IDC_CHECK_NOTCHECK              1085
#define IDC_CHECK_CHECKENDUP            1086
#define IDC_CHECK_CHECKENDNOUP          1087
#define IDC_CHECK_CHECKENDEXEC          1088
#define IDC_SPIN_CHECKMAX               1089
#define IDC_CHECK_SAVEFOLDER            1089
#define IDC_SPIN_ICONINDEX              1090
#define IDC_SPIN_DAY                    1091
#define IDC_SPIN_UPICONINDEX            1091
#define IDC_SPIN_HOU                    1092
#define IDC_SPIN_MIN                    1093
#define IDC_SPIN_MENUINDEX              1094
#define IDC_EDIT_COPYMSG_URL            1095
#define IDC_BUTTON_PUROTOCOL            1096
#define IDC_EDIT_FINDLOCATE             1096
#define IDC_BUTTON_FILESELECT           1097
#define IDC_BUTTON_COMMANDLINE          1098
#define IDC_STATIC_COPYMSG_TITLE        1099
#define IDC_STATIC_COPYMSG_TO           1100
#define IDC_STATIC_COPYMSG_FROM         1101
#define IDC_STATIC_COPYMSG_TOICON       1102
#define IDC_STATIC_COPYMSG_FROMICON     1103
#define IDC_TAB                         1104
#define IDC_STATIC_BANNER               1108
#define IDC_STATIC_COMMANDLINE          1110
#define IDC_CHECK_GENERALUSER           1111
#define IDC_CHECK_FINDSUBFOLDER         1112
#define IDC_CHECK_NAME                  1113
#define IDC_CHECK_FINDNOCHECK           1113
#define IDC_CHECK_CHECKURL              1114
#define WWWC_TREE                       1114
#define IDC_CHECK_OPENURL               1115
#define IDC_BUTTON_SELECT               1115
#define IDC_CHECK_COMMENT               1116
#define IDC_COMBO_FINDSTRING            1116
#define IDC_CHECK_UPICON                1117
#define IDC_CHECK_ERRICON               1118
#define IDC_CHECK_TIMEICON              1119
#define IDC_CHECK_ICON                  1120
#define IDC_CHECK_DATE                  1121
#define IDC_CHECK_NOCHECKICON           1122
#define IDC_BUTTON_SELECT_P             1122
#define IDC_BUTTON_SELECT_T             1123
#define IDC_HOTKEY                      1123
#define IDC_STATIC_HOTKEY               1124
#define IDC_STATIC_MENUINDEX            1125
#define IDC_STATIC_PROTOCOL             1126
#define IDC_LIST_ICON                   1127
#define IDC_EDIT_FILE                   1128
#define IDC_EDIT_INFO                   1133
#define IDC_EDIT_SIZE                   1134
#define ID_MENUITEM_ALLCHECK            40002
#define ID_MENUITEM_CHECK               40003
#define ID_MENUITEM_CHECKEND            40004
#define ID_MENUITEM_INITICON            40005
#define ID_MENUITEM_ALLINITICON         40006
#define ID_MENUITEM_NEWFOLDER           40008
#define ID_KEY_TAB                      40009
#define ID_MENUITEM_DELETE              40010
#define ID_MENUITEM_EDITNAME            40011
#define ID_MENUITEM_PROP                40013
#define ID_MENUITEM_VIEW_ICON           40014
#define ID_MENUITEM_VIEW_SMALLICON      40015
#define ID_MENUITEM_VIEW_LIST           40016
#define ID_MENUITEM_VIEW_REPORT         40017
#define ID_MENUITEM_VIEW_REPORT_LINE    40018
#define ID_MENUITEM_ALLCHECKEND         40020
#define ID_MENUITEM_POP_NEWITEM         40021
#define ID_MENUITEM_CLOSE               40023
#define ID_MENUITEM_CUT_POP             40024
#define ID_KEY_UPDIR                    40033
#define ID_BUTTON40035                  40035
#define ID_MENUITEM_ABOUT               40038
#define ID_BUTTON40039                  40039
#define ID_BUTTON40041                  40041
#define ID_BUTTON40042                  40042
#define ID_BUTTON40043                  40043
#define ID_BUTTON40044                  40044
#define ID_MENUITEM_CHECK_POP           40050
#define ID_MENUITEM_CHECKEND_POP        40051
#define ID_MENUITEM_INITICON_POP        40052
#define ID_MENUITEM_DELETE_POP          40053
#define ID_MENUITEM_EDITNAME_POP        40054
#define ID_MENUITEM_CUT                 40055
#define ID_MENUITEM_COPY                40056
#define ID_MENUITEM_ALLSELECT           40057
#define ID_MENUITEM_SWITCHSELECT        40058
#define ID_MENUITEM_ALLERRORCHECK       40059
#define ID_MENUITEM_PASTE               40060
#define ID_MENUITEM_REFRESH             40061
#define ID_MENUITEM_COPY_POP            40062
#define ID_MENU_DGDP_CUT                40063
#define ID_MENU_DGDP_COPY               40064
#define ID_MENU_DGDP_CANCEL             40065
#define ID_MENUITEM_SORT_ICON           40074
#define ID_MENUITEM_SORT_NAME           40075
#define ID_MENUITEM_SORT_SIZE           40076
#define ID_MENUITEM_SORT_DATE           40077
#define ID_MENUITEM_SORT_URL            40078
#define ID_MENUITEM4_TB_CUSTOM          40079
#define ID_BUTTON40081                  40081
#define ID_BUTTON40082                  40082
#define ID_MENUITEM_VIEW_TB             40085
#define ID_MENUITEM_VIEW_SB             40086
#define ID_KEY_RBUTTON                  40087
#define ID_MENUITEM_UPVIEW              40089
#define ID_MENUITEM_OPTION              40090
#define ID_MENUITEM_CHECKSWITCH         40091
#define ID_MENUITEM_ICON_UP             40092
#define ID_MENUITEM_ICON_ERROR          40093
#define ID_MENUITEM_ICON_TIMEOUT        40094
#define ID_MENUITEM_CHECKSWITCH_POP     40095
#define ID_MENUITEM_PROP_POP            40097
#define ID_MENUITEM_END                 40098
#define ID_MENUITEM_REWINDOW            40099
#define ID_KEY_RETURN                   40100
#define ID_KEY_ESC                      40101
#define ID_BUTTON40102                  40102
#define ID_MENUITEM_AUTOSORT            40103
#define ID_MENUITEM_VIEWUPMSG           40104
#define ID_MENUITEM_UPITEMCLEAR         40105
#define ID_BUTTON40106                  40106
#define ID_MENUITEM_FOLDERTREECHECK     40108
#define ID_BUTTON40109                  40109
#define ID_KEY_PASTE                    40110
#define ID_MENUITEM_SERACH              40111
#define ID_MENUITEM_HELP                40113
#define ID_BUTTON40114                  40114
#define ID_MENUITEM_FOLDERTREECHECK_POP 40116
#define ID_MENUITEM_SERACH_POP          40117
#define ID_MENUITEM_UNDO                40119
#define ID_MENUITEM_PREV_HISTORY        40120
#define ID_MENUITEM_NEXT_HISTORY        40121
#define ID_BUTTON40122                  40122
#define ID_MENUITEM_TBNEW               40122
#define ID_BUTTON40123                  40123
#define ID_MENUITEM_UPSELECT            40124
#define ID_MENUITEM_AUTOCHECK           40125
#define ID_KEY_TABCHANGE                40126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         40130
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
